import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('account profile, language, email, password and legal information', async ({ page }) => {
  const email = `account-${Date.now()}@example.test`;
  const password = 'test-account-password-123';
  await page.goto('/');
  await page.getByRole('button', { name: 'Criar uma conta' }).click();
  await page.getByLabel('E-mail', { exact: true }).fill(email);
  await page.getByLabel(/^Palavra-passe/).fill(password);
  await page.getByRole('button', { name: 'Criar conta', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'O que queres fazer?' })).toBeVisible();
  await expect(page.getByText('Instalação local', { exact: true })).toHaveCount(0);
  expect(await page.locator('link[rel=icon]').getAttribute('href')).toBe('/logo.png');
  await page.locator('.account').click();
  await page.getByRole('button', { name: 'A minha conta' }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByRole('heading', { name: 'A minha conta' })).toBeVisible();
  await expect(dialog.getByLabel('E-mail', { exact: true })).toHaveValue(email);
  await expect(dialog.getByLabel('Nova palavra-passe')).toHaveCount(0);
  await dialog.getByLabel('Nome', { exact: true }).fill('Pessoa de teste');
  await dialog.getByLabel('Idioma', { exact: true }).selectOption('en');
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(dialog.getByRole('status')).toHaveText('Changes saved.');
  await dialog.getByRole('button', { name: 'About and legal' }).click();
  await expect(dialog.getByRole('link', { name: 'Dinis Mago' })).toHaveAttribute('href', 'https://github.com/dinismagoptoficial');
  await dialog.getByText('Privacy and retention', { exact: true }).click();
  await expect(dialog.getByText(/The software author does not receive/)).toBeVisible();
  await dialog.getByRole('button', { name: 'Profile', exact: true }).click();
  await page.screenshot({ path: 'test-results/account-desktop.png', fullPage: true });
  const accessibility = await new AxeBuilder({ page }).include('.account-modal').analyze();
  expect(accessibility.violations).toEqual([]);
  await dialog.getByLabel('E-mail', { exact: true }).fill(`new-${email}`);
  await dialog.getByLabel('Current password to confirm your email').fill(password);
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog.getByRole('status')).toHaveText('Changes saved.');
  await dialog.getByRole('button', { name: 'Security', exact: true }).click();
  await dialog.getByLabel('Current password', { exact: true }).fill(password);
  await dialog.getByLabel('New password', { exact: true }).fill('replacement-password-123');
  await dialog.getByLabel('Confirm password', { exact: true }).fill('replacement-password-123');
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog.getByRole('status')).toHaveText('Changes saved.');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/account-mobile.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Open menu' }).click();
  await page.locator('.account').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByLabel('E-mail', { exact: true }).fill(`new-${email}`);
  await page.getByLabel(/^Password/).fill('replacement-password-123');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'What would you like to do?' })).toBeVisible();
});
